languageCode = "zh-tw"
languageName = "Traditional Chinese (Taiwan)"
weight = 1
title = "Hsuan0223x's Blog"

[params]
  displayName = "zh-tw"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [author]
  name = "hsuan0223x"
   image = "Person_photo.jpg"
   headline = "一個路人。"
   bio = "A little bit about you"
   links = [
     { email = "mailto:hsuan0223x@gmail.com" },
     { github = "https://github.com/hsuan0223x" },
     { telegram = "https://t.me/Hsuan0223x" },
]
