[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 3

[[main]]
  name = "About"
  pageRef = "/about.md"
  weight = 2

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 4
